fix: isAsync is deprecated
ladjs/mongoose-slug-plugin pull request #7
Opened 2019-09-09 18:22 UTC by paullbn

Hello,

This PR solves the following mongoose deprecation warning:

```sh
DeprecationWarning: Mongoose: the `isAsync` option for custom validators is deprecated. Make your async validators return a promise instead: https://mongoosejs.com/docs/validation.html#async-custom-validators
```

2019-09-09 18:24 UTC, niftylettuce requested changes
This actually doesn't need to be asynchronous at all nor return a Promise, I think we can just throw an error?

2019-09-09 18:57 UTC, paullbn commented
Ok, i thought there was a reason i didn't know that the validator was asynchronous with isAsync set to true, so i've just put it in a promise.

I'll update the PR as soon as i can

2019-12-31 22:00 UTC, luluhoc commented
Will you update it?

2019-12-31 22:30 UTC, niftylettuce commented
PR welcome!

2020-01-02 11:21 UTC, closed without merging

2020-01-02 11:22 UTC, niftylettuce commented
v2.0.2 has been released to npm with this fixed

```sh
npm install mongoose-slug-plugin@latest
```

or with yarn:

```sh
yarn add mongoose-slug-plugin@latest
```